import type { Tile } from './types'

// Simplified Monopoly board (0..39)
export const defaultBoard: Tile[] = [
  { id: 0, name: 'GO', type: 'go' },
  { id: 1, name: 'Mediterranean Ave', type: 'property', color: '#8b5cf6', price: 60, rent: 2 },
  { id: 2, name: 'Community Chest', type: 'chest' },
  { id: 3, name: 'Baltic Ave', type: 'property', color: '#8b5cf6', price: 60, rent: 4 },
  { id: 4, name: 'Income Tax', type: 'tax', price: 200 },
  { id: 5, name: 'Reading Railroad', type: 'railroad', price: 200, rent: 25 },
  { id: 6, name: 'Oriental Ave', type: 'property', color: '#22c55e', price: 100, rent: 6 },
  { id: 7, name: 'Chance', type: 'chance' },
  { id: 8, name: 'Vermont Ave', type: 'property', color: '#22c55e', price: 100, rent: 6 },
  { id: 9, name: 'Connecticut Ave', type: 'property', color: '#22c55e', price: 120, rent: 8 },
  { id: 10, name: 'Jail / Just Visiting', type: 'jail' },
  { id: 11, name: 'St. Charles Place', type: 'property', color: '#ef4444', price: 140, rent: 10 },
  { id: 12, name: 'Electric Company', type: 'utility', price: 150, rent: 10 },
  { id: 13, name: 'States Ave', type: 'property', color: '#ef4444', price: 140, rent: 10 },
  { id: 14, name: 'Virginia Ave', type: 'property', color: '#ef4444', price: 160, rent: 12 },
  { id: 15, name: 'Pennsylvania Railroad', type: 'railroad', price: 200, rent: 25 },
  { id: 16, name: 'St. James Place', type: 'property', color: '#f59e0b', price: 180, rent: 14 },
  { id: 17, name: 'Community Chest', type: 'chest' },
  { id: 18, name: 'Tennessee Ave', type: 'property', color: '#f59e0b', price: 180, rent: 14 },
  { id: 19, name: 'New York Ave', type: 'property', color: '#f59e0b', price: 200, rent: 16 },
  { id: 20, name: 'Free Parking', type: 'freeparking' },
  { id: 21, name: 'Kentucky Ave', type: 'property', color: '#ef4444', price: 220, rent: 18 },
  { id: 22, name: 'Chance', type: 'chance' },
  { id: 23, name: 'Indiana Ave', type: 'property', color: '#ef4444', price: 220, rent: 18 },
  { id: 24, name: 'Illinois Ave', type: 'property', color: '#ef4444', price: 240, rent: 20 },
  { id: 25, name: 'B. & O. Railroad', type: 'railroad', price: 200, rent: 25 },
  { id: 26, name: 'Atlantic Ave', type: 'property', color: '#22d3ee', price: 260, rent: 22 },
  { id: 27, name: 'Ventnor Ave', type: 'property', color: '#22d3ee', price: 260, rent: 22 },
  { id: 28, name: 'Water Works', type: 'utility', price: 150, rent: 10 },
  { id: 29, name: 'Marvin Gardens', type: 'property', color: '#22d3ee', price: 280, rent: 24 },
  { id: 30, name: 'Go To Jail', type: 'gotojail' },
  { id: 31, name: 'Pacific Ave', type: 'property', color: '#10b981', price: 300, rent: 26 },
  { id: 32, name: 'North Carolina Ave', type: 'property', color: '#10b981', price: 300, rent: 26 },
  { id: 33, name: 'Community Chest', type: 'chest' },
  { id: 34, name: 'Pennsylvania Ave', type: 'property', color: '#10b981', price: 320, rent: 28 },
  { id: 35, name: 'Short Line', type: 'railroad', price: 200, rent: 25 },
  { id: 36, name: 'Chance', type: 'chance' },
  { id: 37, name: 'Park Place', type: 'property', color: '#3b82f6', price: 350, rent: 35 },
  { id: 38, name: 'Luxury Tax', type: 'tax', price: 100 },
  { id: 39, name: 'Boardwalk', type: 'property', color: '#3b82f6', price: 400, rent: 50 },
]

