import type { Property } from "./interfaces";
import manifest from "./manifest_sepolia.json";
export const PROPERTIES: Property[] = [
  {
    name: "GO",
    price: 0,
    rent: [0],
    color: "",
    position: 0,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Mediterranean Avenue",
    price: 60,
    rent: [2, 10, 30, 90, 160, 250],
    color: "bg-purple-900",
    position: 1,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 50,
  },
  {
    name: "Community Chest",
    price: 0,
    rent: [0],
    color: "",
    position: 2,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Baltic Avenue",
    price: 60,
    rent: [4, 20, 60, 180, 320, 450],
    color: "bg-purple-900",
    position: 3,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 50,
  },
  {
    name: "Income Tax",
    price: 0,
    rent: [0],
    color: "",
    position: 4,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Reading Railroad",
    price: 200,
    rent: [25, 50, 100, 200],
    color: "",
    position: 5,
    owner: null,
    houses: 0,
    type: "railroad",
  },
  {
    name: "Oriental Avenue",
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    color: "bg-sky-400",
    position: 6,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 50,
  },
  {
    name: "Chance",
    price: 0,
    rent: [0],
    color: "",
    position: 7,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Vermont Avenue",
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    color: "bg-sky-400",
    position: 8,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 50,
  },
  {
    name: "Connecticut Avenue",
    price: 120,
    rent: [8, 40, 100, 300, 450, 600],
    color: "bg-sky-400",
    position: 9,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 50,
  },
  {
    name: "Just Visiting",
    price: 0,
    rent: [0],
    color: "",
    position: 10,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "St. Charles Place",
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    color: "bg-pink-600",
    position: 11,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 100,
  },
  {
    name: "Electric Company",
    price: 150,
    rent: [0],
    color: "",
    position: 12,
    owner: null,
    houses: 0,
    type: "utility",
  },
  {
    name: "States Avenue",
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    color: "bg-pink-600",
    position: 13,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 100,
  },
  {
    name: "Virginia Avenue",
    price: 160,
    rent: [12, 60, 180, 500, 700, 900],
    color: "bg-pink-600",
    position: 14,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 100,
  },
  {
    name: "Pennsylvania Railroad",
    price: 200,
    rent: [25, 50, 100, 200],
    color: "",
    position: 15,
    owner: null,
    houses: 0,
    type: "railroad",
  },
  {
    name: "St. James Place",
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    color: "bg-orange-600",
    position: 16,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 100,
  },
  {
    name: "Community Chest",
    price: 0,
    rent: [0],
    color: "",
    position: 17,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Tennessee Avenue",
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    color: "bg-orange-600",
    position: 18,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 100,
  },
  {
    name: "New York Avenue",
    price: 200,
    rent: [16, 80, 220, 600, 800, 1000],
    color: "bg-orange-600",
    position: 19,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 100,
  },
  {
    name: "Free Parking",
    price: 0,
    rent: [0],
    color: "",
    position: 20,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Kentucky Avenue",
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    color: "bg-red-600",
    position: 21,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 150,
  },
  {
    name: "Chance",
    price: 0,
    rent: [0],
    color: "",
    position: 22,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Indiana Avenue",
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    color: "bg-red-600",
    position: 23,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 150,
  },
  {
    name: "Illinois Avenue",
    price: 240,
    rent: [20, 100, 300, 750, 925, 1100],
    color: "bg-red-600",
    position: 24,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 150,
  },
  {
    name: "B. & O. Railroad",
    price: 200,
    rent: [25, 50, 100, 200],
    color: "",
    position: 25,
    owner: null,
    houses: 0,
    type: "railroad",
  },
  {
    name: "Atlantic Avenue",
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    color: "bg-yellow-500",
    position: 26,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 150,
  },
  {
    name: "Ventnor Avenue",
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    color: "bg-yellow-500",
    position: 27,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 150,
  },
  {
    name: "Water Works",
    price: 150,
    rent: [0],
    color: "",
    position: 28,
    owner: null,
    houses: 0,
    type: "utility",
  },
  {
    name: "Marvin Gardens",
    price: 280,
    rent: [24, 120, 360, 850, 1025, 1200],
    color: "bg-yellow-500",
    position: 29,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 150,
  },
  {
    name: "Go To Jail",
    price: 0,
    rent: [0],
    color: "",
    position: 30,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Pacific Avenue",
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    color: "bg-green-600",
    position: 31,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 200,
  },
  {
    name: "North Carolina Avenue",
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    color: "bg-green-600",
    position: 32,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 200,
  },
  {
    name: "Community Chest",
    price: 0,
    rent: [0],
    color: "",
    position: 33,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Pennsylvania Avenue",
    price: 320,
    rent: [28, 150, 450, 1000, 1200, 1400],
    color: "bg-green-600",
    position: 34,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 200,
  },
  {
    name: "Short Line",
    price: 200,
    rent: [25, 50, 100, 200],
    color: "",
    position: 35,
    owner: null,
    houses: 0,
    type: "railroad",
  },
  {
    name: "Chance",
    price: 0,
    rent: [0],
    color: "",
    position: 36,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Park Place",
    price: 350,
    rent: [35, 175, 500, 1100, 1300, 1500],
    color: "bg-blue-900",
    position: 37,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 200,
  },
  {
    name: "Luxury Tax",
    price: 0,
    rent: [0],
    color: "",
    position: 38,
    owner: null,
    houses: 0,
    type: "special",
  },
  {
    name: "Boardwalk",
    price: 400,
    rent: [50, 200, 600, 1400, 1700, 2000],
    color: "bg-blue-900",
    position: 39,
    owner: null,
    houses: 0,
    type: "property",
    housePrice: 200,
  },
];

export const AVAILABLE_PIECES = [
  "🚗",
  "🎩",
  "🚢",
  "🐕",
  "🐈",
  "👞",
  "🎸",
  "⚓",
];
export const PLAYER_COLORS = [
  "bg-blue-600",
  "bg-red-600",
  "bg-green-600",
  "bg-yellow-600",
];

export const SOCKET_SERVER_URL = "https://starkcity-tl4b.vercel.app";
export const WORLD_ADDRESS = manifest.contracts[0].address;
